version: '2'

services:
  postgres:
    image: postgres:10
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
  sonarqube:
    image: owasp/sonarqube:latest
    ports:
      - '9000:9000'
#    entrypoint: ['sleep','1500']
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
volumes:
  sonarqube_data:
    driver: local
  sonarqube_logs:
    driver: local
  postgres_data:
    driver: local


