FROM sonarqube:8.4.0-enterprise

run wget https://github.com/edwinyangzh/sonar-java-i18n-checks/releases/download/v0.1.0/java-i18n-rules-0.1.0.jar -O /opt/sonarqube/extensions/plugins/java-i18n-rules-0.1.0.jar    && \
    wget https://github.com/spotbugs/sonar-findbugs/releases/download/3.11.1/sonar-findbugs-plugin-3.11.1.jar -O /opt/sonarqube/extensions/plugins/sonar-findbugs-plugin-3.11.1.jar
